### ISSUE TITLE
hashGenesisBlock

### ISSUE THREAD

**Issue by g01dt00th** [216k155/bhcoin#1]
ool@ubuntu:~$ bhcoind
bhcoind: chainparams.cpp:78: CMainParams::CMainParams(): Assertion `hashGenesisBlock == uint256("")' failed.
Aborted (core dumped)

after compile :(

**Comment by 216k155** [comment]
You need to // 2 asser in chainparam.cpp.
Open chainparam.cpp and follow the guide in there.
